import os
from glob import glob
from typing import List, Optional

import pandas as pd


def list_data_files(
    data_dir: str = "data",
    symbol_filter: Optional[str] = None,
) -> List[str]:
    """
    List CSV files in the data directory.
    Optionally filter by symbol substring, e.g. 'BTC_USD'.
    """
    pattern = os.path.join(data_dir, "*.csv")
    files = glob(pattern)

    if symbol_filter:
        files = [f for f in files if symbol_filter in os.path.basename(f)]

    return sorted(files)


def load_price_data(
    data_dir: str = "data",
    symbol_filter: Optional[str] = None,
) -> pd.DataFrame:
    """
    Load and clean CSVs generated by our yfinance ingestion.

    Yahoo Finance crypto format includes:
      Row 1: column categories
      Row 2: ticker symbols
      Row 3: "timestamp,,,,,,"
      Row 4+: actual data
    """
    files = list_data_files(data_dir=data_dir, symbol_filter=symbol_filter)
    if not files:
        raise FileNotFoundError(
            f"No CSV files found in {data_dir} for filter={symbol_filter}"
        )

    dfs = []
    for path in files:
        df = pd.read_csv(
            path,
            skiprows=2,  # skip "Price,...", "Ticker,..."
            header=0,    # use the third row ("timestamp,,,,,,") as header
        )

        # Drop rows where timestamp literally equals "timestamp"
        df = df[df["timestamp"] != "timestamp"]

        # Clean column names
        df.columns = [
            "timestamp",
            "adj_close",
            "close",
            "high",
            "low",
            "open",
            "volume",
        ]

        # Convert timestamp to datetime
        df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

        # Remove bad rows
        df = df.dropna(subset=["timestamp"])

        df = df.set_index("timestamp").sort_index()
        dfs.append(df)

    combined = pd.concat(dfs)
    combined = combined[~combined.index.duplicated(keep="last")]
    combined = combined.sort_index()
    return combined
